[app]
    name        = "golang-backend-example"
    environment = "development"
    port        = 8000

[database]
    host        = "127.0.0.1" # Change to localhost on local machine development
    port        = 5432
    name        = "backend_golang_example"
    username    = "postgres"
    password    = "password"
    sslmode     = "disable"
